# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[('config.yaml', '.'), ('db\\schema.sql', 'db')],
    hiddenimports=[
        '_socket',
        'socket',
        'multiprocessing',
        'multiprocessing.reduction',
        'multiprocessing.context',
        'multiprocessing.popen_spawn_win32',
        'pystray',
        'pystray._win32',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        'PIL.ImageFont',
        'langchain_google_genai',
        'langchain_google_genai.chat_models',
        'google.generativeai',
        'langchain_core',
        'langchain_core.messages',
        'langchain_core.outputs',
        'langgraph',
        'langgraph.graph',
        'infra',
        'infra.metrics',
        'runtime',
        'runtime.event_bus',
        'runtime.circuit_breaker',
        'runtime.commands',
        'runtime.single_instance',
        'version',
        'branding',
        'classifiers',
        'classifiers.decision_cache',
        'core',
        'core.agent_orchestrator',
        'core.llm_engine',
        'core.settings_manager',
        'modules',
        'modules.crud_executor',
        'modules.file_watcher',
        'modules.history',
        'modules.multimodal_parser',
        'modules.periodic_scanner',
        'modules.rules_engine',
        'modules.tray_icon',
        'db',
        'db.database_manager',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=['rthook_fix_socket.py'],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='NAPSorter',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='NAPSorter',
)
